import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        white: "#ffffff",
        "color-white": "#ffffff",
        maroon: {
          DEFAULT: "#8b1a1a",
          50: "#8b1a1a",
          100: "#8b1a1a",
          200: "#8b1a1a",
          300: "#8b1a1a",
          400: "#8b1a1a",
          500: "#8b1a1a",
          600: "#8b1a1a",
          700: "#8b1a1a",
          800: "#8b1a1a",
          900: "#8b1a1a",
          950: "#8b1a1a",
        },
        "color-maroon": "#8b1a1a",
        brand: {
          maroon: "#8b1a1a",
          red: "#8b1a1a",
          crimson: "#8b1a1a",
          redDark: "#8b1a1a",
          redLight: "#ffffff",
          "red-dark": "#8b1a1a",
          "red-50": "#ffffff",
          accent: "#8b1a1a",
          // Backward compat aliases mapped strictly to brand maroon/white
          purple: "#8b1a1a",
          purpleDark: "#8b1a1a",
          purpleLight: "#ffffff",
          violet: "#8b1a1a",
          gradientStart: "#8b1a1a",
          gradientEnd: "#8b1a1a",
        },
        background: "var(--color-white)",
        surface: "var(--color-white)",
        "surface-alt": "var(--color-white)",
        "surface-muted": "var(--color-white)",
        // Semantic neutrals
        ink: "#141414",
        body: "#4B4B4B",
        muted: "#6B6B6B",
        line: "#E7E7E7",
        text: {
          primary: "#141414",
          secondary: "#4B4B4B",
          tertiary: "#6B6B6B",
        },
        border: {
          light: "#E7E7E7",
          DEFAULT: "#E7E7E7",
          subtle: "#F3F3F3",
          maroon: "#8b1a1a",
          purple: "#E7E7E7",
        },
      },
      fontFamily: {
        display: ["var(--font-display)", "sans-serif"],
        accent: ["var(--font-accent)", "serif"],
        body: ["var(--font-body)", "sans-serif"],
        sans: ["var(--font-body)", "sans-serif"],
        heading: ["var(--font-display)", "sans-serif"],
        serif: ["var(--font-accent)", "serif"],
        editorial: ["var(--font-accent)", "serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
      },
      letterSpacing: {
        tightest: "-0.05em",
        tighter: "-0.03em",
      },
      borderRadius: {
        none: "0px",
        sm: "4px",
        DEFAULT: "6px",
        md: "6px",
        lg: "8px",
        xl: "8px",
        "2xl": "8px",
        "3xl": "8px",
        "4xl": "8px",
        full: "9999px",
      },
      boxShadow: {
        none: "none",
        DEFAULT: "none",
        subtle: "0 1px 3px rgba(139, 26, 26, 0.05)",
        elevated: "0 4px 12px rgba(139, 26, 26, 0.05)",
        // Reset decorative heavy shadows
        soft: "none",
        card: "none",
        floating: "none",
        "purple-btn": "none",
        "maroon-btn": "none",
        "maroon-bloom": "none",
        "red-btn": "none",
        chiclet: "none",
      },
    },
  },
  plugins: [],
};
export default config;
