import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--bg-white)",
        surface: "var(--bg-white)",
        "surface-alt": "var(--bg-white)",
        "surface-muted": "var(--bg-white)",
        white: "#FAF8F5",
        maroon: {
          50: "#FDF2F2",
          100: "#FDE8E8",
          200: "#FBD5D5",
          300: "#F8B4B4",
          400: "#F98080",
          500: "#C81E1E",
          600: "#A31F1F",
          700: "#8B1A1A",
          800: "#7A1F2B",
          900: "#540F0F",
          950: "#3D0B0B",
        },
        brand: {
          maroon: "#8B1A1A",
          red: "#8B1A1A",
          crimson: "#A31F1F",
          redDark: "#7A1F2B",
          redLight: "#F7EBEB",
          "red-dark": "#7A1F2B",
          "red-50": "#F7EBEB",
          accent: "#8B1A1A",
          // Backward compat aliases mapped strictly to brand maroon/white
          purple: "#8B1A1A",
          purpleDark: "#7A1F2B",
          purpleLight: "var(--bg-white)",
          violet: "#8B1A1A",
          gradientStart: "#8B1A1A",
          gradientEnd: "#8B1A1A",
        },
        // Semantic neutrals
        ink: "#141414",
        body: "#4B4B4B",
        muted: "#6B6B6B",
        line: "#E7E7E7",
        text: {
          primary: "#141414",
          secondary: "#4B4B4B",
          tertiary: "#6B6B6B",
        },
        border: {
          light: "#E7E7E7",
          DEFAULT: "#E7E7E7",
          subtle: "#F3F3F3",
          maroon: "#8B1A1A",
          purple: "#E7E7E7",
        },
      },
      fontFamily: {
        display: ["var(--font-display)", "sans-serif"],
        accent: ["var(--font-accent)", "serif"],
        body: ["var(--font-body)", "sans-serif"],
        sans: ["var(--font-body)", "sans-serif"],
        heading: ["var(--font-display)", "sans-serif"],
        serif: ["var(--font-accent)", "serif"],
        editorial: ["var(--font-accent)", "serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      letterSpacing: {
        tightest: "-0.05em",
        tighter: "-0.03em",
      },
      borderRadius: {
        none: "0px",
        sm: "4px",
        DEFAULT: "6px",
        md: "6px",
        lg: "8px",
        xl: "8px",
        "2xl": "8px",
        "3xl": "8px",
        "4xl": "8px",
        full: "9999px",
      },
      boxShadow: {
        none: "none",
        DEFAULT: "none",
        subtle: "0 1px 3px rgba(139, 26, 26, 0.05)",
        elevated: "0 4px 12px rgba(139, 26, 26, 0.05)",
        // Reset decorative heavy shadows
        soft: "none",
        card: "none",
        floating: "none",
        "purple-btn": "none",
        "maroon-btn": "none",
        "maroon-bloom": "none",
        "red-btn": "none",
        chiclet: "none",
      },
    },
  },
  plugins: [],
};
export default config;
